language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: YdtGOUT2EQXlumPfTRIxfgTRpfHCjxN8lu9+Kbve1YNRTn3HHrZ/tQwdASwxGY/5737uvtlOxOXPj8+kkp/g3o1JoCtwJifGa1XAAw7mjiO5cpYCxHS7iPHIbe/e8c8AWpgt0xQZawt4/s74T6zEjKUN9RCvJa7Idl8pLgfCQw4x8cuOvy9909yLzqrD7H/jYw0RQj6XxVmmA+0cK/8CaF5c1783fqbJAvCOlw8K9YHJjRvWcdXBSu4/VCNKu4aYfYfghWsblWdPsB606y2PtejIvtiwVrFf9p9vKlplJlOy8CRHoLVNXhbQtNHj0glau3JMXVZxotC0ZTDIEA9d+AtaSGS6E+/nlmGp5IlWrZcni0X9/DZ2IbR2KnsXbgbWIZnkGZJ9GS94XqczHLxtZHIKp8jAgPnN22d9KKfXyiQE2qlW8uAZxgmODpdVJfOqbIndCrGQI753jPMGn9ttIaYD5RNSmkmMGX+JZLge6IyK14PJSO1dx5sWeIBxsMruKrdo2EixmfyMvcsfL9PzUR1uhSmZw8sI3CxUSAF6ZQnntDPafh/ao5VhX0TMB4yKEZBdmR1KPswrlygxBu73Ea30ejOP22LBnbWPJsNJ1gAzNFGKEynAsOe5fK5KDNDdukR2uuZg+ZO4CwADn5XygjPx32eSnslQ4VcGMrbrDR4=
  app: dry-dusk-09473
  on:
    repo: Acosta816/Blogful-API-2020-full
  skip_cleanup: 'true'
